homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

#introduction:

frontend:

config:

#http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

logger:
  default: warn
  logs:
    homeassistant.components.sensor: error

updater:
  reporting: no

discovery:
  ignore: 
    - google_cast

light:
  platform: hue

hue:
  bridges:
    - host: !secret huehost

history:

logbook:

sun:

#mqtt:

media_player:
  - platform: kodi
    host: !secret kodi_host
    name: Cinebar
    turn_off_action:
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: System.Shutdown
  - platform: yamaha
    scan_interval: 30
    host: !secret receiver_host
    name: Receiver
    zone_ignore:
      - "zone 2"
    source_ignore:
      - V-AUX
      - Napster
      - NET RADIO
      - AV1
      - AV2
      - AV3
      - AV4
      - AV5
      - AV6
      - UAW
      - iPod
      - iPod (USB)
      - AUDIO1
      - AUDIO2
      - Bluetooth
      - USB
    source_names:
      HDMI1: "Cinebar"
      HDMI2: "Nintendo Switch"
      HDMI3: "Playstation 3"
      HDMI4: "Chrome Cast"
      HDMI5: "Spare"
      PHONO: "Vinyl"

netatmo:
  api_key: !secret netatmo_api-key
  secret_key: !secret netatmo_secret-key
  username: !secret netatmo_username
  password: !secret netatmo_password

group: !include groups.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml

input_boolean: !include input-booleans.yaml
script: !include scripts.yaml
automation: !include_dir_merge_list automation

