homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  packages: !include_dir_named packages
  customize: !include customize.yaml

#introduction:

system_health:

frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

logger:
  default: info
  logs:
    homeassistant.components.sensor: fatal

updater:
  reporting: no

discovery:
  ignore: 
    - netgear_router

light:
  platform: hue

hue:
  bridges:
    - host: !secret huehost

history:

logbook:

sun:

#mqtt:

#python_script:

device_tracker:
  - platform: ping
    home_interval: 5
    hosts:
      handy_1: !secret track_lugi
      handy_2: !secret track_nine

cast:
    
media_player:
  - platform: kodi
    host: !secret kodi_host
    name: Cinebar
    turn_off_action:
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: System.Shutdown
  - platform: yamaha
    scan_interval: 30
    host: !secret receiver_host
    name: Receiver
    zone_ignore:
      - "zone 2"
    source_ignore:
      - V-AUX
      - Napster
      - NET RADIO
      - AV1
      - AV2
      - AV3
      - AV4
      - AV5
      - AV6
      - UAW
      - iPod
      - iPod (USB)
      - AUDIO1
      - AUDIO2
      - Bluetooth
      - USB
      - PHONO
    source_names:
      HDMI1: "Cinebar"
      HDMI2: "Nintendo Switch"
      HDMI3: "Playstation 4"
      HDMI4: "Chrome Cast"
      HDMI5: "Steam Link"

netatmo:
  api_key: !secret netatmo_api-key
  secret_key: !secret netatmo_secret-key
  username: !secret netatmo_username
  password: !secret netatmo_password

group: !include groups.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml

input_boolean: !include input-booleans.yaml
input_text: !include input-texts.yaml
input_number: !include input-numbers.yaml
script: !include scripts.yaml
timer: !include timers.yaml
automation: !include_dir_merge_list automation
