homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

#introduction:

frontend:

config:

#http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

logger:
  default: error

updater:
  reporting: no

discovery:
  ignore: 
    - google_cast

light:
  platform: hue

history:

logbook:

sun:

media_player:
  - platform: kodi
    host: !secret kodi_host
    name: Cinebar
  - platform: yamaha
    name: Receiver
    source_ignore:
      - V-AUX
      - Napster
      - NET RADIO
      - AV1
      - AV2
      - AV3
      - AV4
      - AV5
      - AV6
      - UAW
      - iPod
      - iPod (USB)
      - AUDIO1
      - AUDIO2
      - Bluetooth
      - USB
    source_names:
      HDMI1: Cinebar
      HDMI2: Nintendo Switch
      HDMI3: Playstation 3
      HDMI4: Chrome Cast
      HDMI5: Spare

group: !include groups.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml

input_boolean: !include input-booleans.yaml
automation: !include_dir_merge_list automation

