homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone

#introduction:

frontend:

config:

#http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:
  reporting: no

discovery:

light:
  platform: hue

history:

logbook:

sun:

media_player:
  - platform: kodi
    host: !secret kodi_host
    name: Cinebar

group: !include groups.yaml
