- platform: command_line
  name: 'Strom Receiver'
  command: "curl -s -X GET 'http://home-socket.home.lugipfupf.ch/?cmd=511&json=%7B%22sn%22:%22SWP6023002000861%22%7D'"
  value_template: '{{ value_json.data.watt[3] }}'
  unit_of_measurement: 'W'
  scan_interval: 10

- platform: command_line
  name: 'Strom Game'
  command: "curl -s -X GET 'http://home-socket.home.lugipfupf.ch/?cmd=511&json=%7B%22sn%22:%22SWP6023002000861%22%7D'"
  value_template: '{{ value_json.data.watt[2] }}'
  unit_of_measurement: 'W'
  scan_interval: 10

- platform: command_line
  name: 'Strom ChromeCast'
  command: "curl -s -X GET 'http://home-socket.home.lugipfupf.ch/?cmd=511&json=%7B%22sn%22:%22SWP6023002000861%22%7D'"
  value_template: '{{ value_json.data.watt[4] }}'
  unit_of_measurement: 'W'
  scan_interval: 10

- platform: command_line
  name: 'Strom Raspi'
  command: "curl -s -X GET 'http://home-socket.home.lugipfupf.ch/?cmd=511&json=%7B%22sn%22:%22SWP6023002000861%22%7D'"
  value_template: '{{ value_json.data.watt[5] }}'
  unit_of_measurement: 'W'
  scan_interval: 10

- platform: command_line
  name: 'Strom Beamer'
  command: "curl -s -X GET 'http://home-socket.home.lugipfupf.ch/?cmd=511&json=%7B%22sn%22:%22SWP6023002000861%22%7D'"
  value_template: '{{ value_json.data.watt[0] }}'
  unit_of_measurement: 'W'
  scan_interval: 10

- platform: rest
  name: 'Aare Temperatur'
  resource: http://aare.schwumm.ch/aare.json
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'
  scan_interval: 3600

- platform: rest
  name: 'Aare Durchfluss'
  resource: http://aare.schwumm.ch/aare.json
  unit_of_measurement: "m3/s"
  value_template: '{{ value_json.flow }}'
  scan_interval: 3600

- platform: rest
  name: 'Aare Hohe'
  resource: http://aare.schwumm.ch/aare.json
  unit_of_measurement: "m ü M"
  value_template: '{{ value_json.height }}'
  scan_interval: 3600
