- alias: 'Shutdown Cinebar'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "off") }}'
  action:
    service: media_player.turn_off
    entity_id: media_player.cinebar
