- alias: "Media player paused/stopped"
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") and (is_state("media_player.cinebar", "idle") or is_state("media_player.cinebar", "paused")) }}'
  action:
    service: scene.turn_on
    entity_id: scene.movie_menu

- alias: "Media player playing"
  trigger:
    platform: template
    value_template: '{{ is_state("media_player.cinebar", "playing") }}'
  action:
    service: scene.turn_on
    entity_id: scene.movie_playing
