- alias: 'Receiver Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.strom_receiver.state) < 1 and (is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_cast", "on") or is_state("input_boolean.mediacontrol_ps3", "on") or is_state("input_boolean.mediacontrol_switch", "on")) }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_receiver

- alias: 'Cinebar Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") and float(states.sensor.strom_receiver.state) > 40 }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_raspi

- alias: 'Beamer Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_cast", "on") or is_state("input_boolean.mediacontrol_ps3", "on") or is_state("input_boolean.mediacontrol_switch", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_beamer

- alias: 'Game Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_switch", "on") or is_state("input_boolean.powercontrol_switch", "on") or is_state("input_boolean.mediacontrol_ps3", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_game
