- alias: 'Receiver Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_switch", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_receiver

- alias: 'Receiver einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") }}'
  action:
    service: media_player.turn_on
    data:
      entity_id: media_player.receiver
