- alias: 'Receiver Standby'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.strom_receiver.state) > 50 and (is_state("input_boolean.mediacontrol_movies", "off") and is_state("input_boolean.mediacontrol_cast", "off") and is_state("input_boolean.mediacontrol_ps3", "off") and is_state("input_boolean.mediacontrol_switch", "off")) }}'
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.receiver

- alias: 'Receiver Strom ausschalten'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.strom_receiver.state) < 50 and (is_state("input_boolean.mediacontrol_movies", "off") and is_state("input_boolean.mediacontrol_cast", "off") and is_state("input_boolean.mediacontrol_ps3", "off") and is_state("input_boolean.mediacontrol_switch", "off")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.powerstate_receiver
