# - alias: 'Receiver einschalten'
#   trigger:
#     platform: template
#     value_template: '{{ float(states.sensor.strom_receiver.state) > 10 (is_state("input_boolean.mediacontrol_phono", "on") or is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_cast", "on") or is_state("input_boolean.mediacontrol_ps3", "on") or is_state("input_boolean.mediacontrol_switch", "on")) }}'
#   action:
#     service: media_player.turn_on
#     data:
#       entity_id: media_player.receiver

- alias: 'Receiver Eingang Phono'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.receiver_state", "on") }}'
  condition:
    condition: state
    entity_id: input_boolean.mediacontrol_phono
    state: 'on'
  action:
    service: script.receiver_select_source_phono

# - alias: 'Receiver Eingang Cinebar.'
#   trigger:
#     platform: template
#     value_template: '{{ float(states.sensor.strom_receiver.state) > 10 and is_state("input_boolean.mediacontrol_movies", "on") }}'
#   action:
#     service: script.receiver_select_source_hdmi1
#
#- alias: 'Receiver Eingang Game.'
#  trigger:
#    platform: template
#    value_template: '{{ is_state("input_boolean.mediacontrol_switch", "on") and float(states.sensor.strom_receiver.state) > 40 }}'
#  action:
#    service: media_player.select_source
#    data:
#      entity_id: media_player.receiver
#      source: "HDMI5"
