- alias: 'Receiver einschalten'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.strom_receiver.state) > 10 and float(states.sensor.strom_receiver.state) < 30 }}'
  action:
    service: media_player.turn_on
    data:
      entity_id: media_player.receiver

#- alias: 'Receiver Eingang Cinebar.'
#  trigger:
#    platform: template
#    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") and float(states.sensor.strom_receiver.state) > 40) }}'
#  action:
#    service: media_player.select_source
#    data:
#      entity_id: media_player.receiver
#      source: "HDMI1"
#
#- alias: 'Receiver Eingang Game.'
#  trigger:
#    platform: template
#    value_template: '{{ is_state("input_boolean.mediacontrol_switch", "on") and float(states.sensor.strom_receiver.state) > 40) }}'
#  action:
#    service: media_player.select_source
#    data:
#      entity_id: media_player.receiver
#      source: "HDMI5"
