- alias: 'Receiver Eingang Cinebar.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.receiver
      source: "Cinebar"
